-- ==========================================================
-- SafeMind - Base de datos Supabase
-- Puedes ejecutar este archivo en SQL Editor.
-- ==========================================================

-- 1) PROGRESO DE LOS 15 NIVELES
CREATE TABLE IF NOT EXISTS public."Progreso_niveles" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  usuario_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  correo TEXT,
  modulo INTEGER NOT NULL CHECK (modulo BETWEEN 1 AND 3),
  nivel INTEGER NOT NULL CHECK (nivel BETWEEN 1 AND 5),
  porcentaje INTEGER NOT NULL DEFAULT 0 CHECK (porcentaje BETWEEN 0 AND 100),
  completado BOOLEAN NOT NULL DEFAULT FALSE,
  actualizado TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS progreso_usuario_modulo_nivel_idx
ON public."Progreso_niveles" (usuario_id, modulo, nivel);

ALTER TABLE public."Progreso_niveles" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "ver progreso propio" ON public."Progreso_niveles";
CREATE POLICY "ver progreso propio"
ON public."Progreso_niveles"
FOR SELECT TO authenticated
USING (auth.uid() = usuario_id);

DROP POLICY IF EXISTS "crear progreso propio" ON public."Progreso_niveles";
CREATE POLICY "crear progreso propio"
ON public."Progreso_niveles"
FOR INSERT TO authenticated
WITH CHECK (auth.uid() = usuario_id);

DROP POLICY IF EXISTS "actualizar progreso propio" ON public."Progreso_niveles";
CREATE POLICY "actualizar progreso propio"
ON public."Progreso_niveles"
FOR UPDATE TO authenticated
USING (auth.uid() = usuario_id)
WITH CHECK (auth.uid() = usuario_id);

-- 2) HISTORIAL DE REGISTRO / INICIO DE SESIÓN
CREATE TABLE IF NOT EXISTS public.registros_acceso (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  correo TEXT NOT NULL,
  tipo TEXT NOT NULL CHECK (tipo IN ('registro', 'inicio_sesion')),
  fecha TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.registros_acceso ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "crear registro de acceso propio" ON public.registros_acceso;
CREATE POLICY "crear registro de acceso propio"
ON public.registros_acceso
FOR INSERT TO authenticated
WITH CHECK (auth.uid() = usuario_id);

DROP POLICY IF EXISTS "ver registros de acceso propios" ON public.registros_acceso;
CREATE POLICY "ver registros de acceso propios"
ON public.registros_acceso
FOR SELECT TO authenticated
USING (auth.uid() = usuario_id);

-- 3) RESULTADOS DEL MODO MASTER
CREATE TABLE IF NOT EXISTS public.resultados_master (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  correo TEXT NOT NULL,
  correctas INTEGER NOT NULL DEFAULT 0,
  incorrectas INTEGER NOT NULL DEFAULT 0,
  total_preguntas INTEGER NOT NULL DEFAULT 25,
  porcentaje NUMERIC(5,2) NOT NULL DEFAULT 0,
  aprobado BOOLEAN NOT NULL DEFAULT FALSE,
  fecha TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.resultados_master ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "crear resultado master propio" ON public.resultados_master;
CREATE POLICY "crear resultado master propio"
ON public.resultados_master
FOR INSERT TO authenticated
WITH CHECK (auth.uid() = usuario_id);

DROP POLICY IF EXISTS "ver resultado master propio" ON public.resultados_master;
CREATE POLICY "ver resultado master propio"
ON public.resultados_master
FOR SELECT TO authenticated
USING (auth.uid() = usuario_id);
